# Generated by Django 5.0 on 2024-01-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_hub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={
                (
                    "candidate_first_name", "candidate_last_name", "email"
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={
                (
                    "employee_first_name", "employee_last_name", "email"
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="employer",
            unique_together={
                (
                    "employer_first_name",
                    "employer_last_name",
                    "email",
                    "company_profile",
                )
            },
        ),
    ]
