# Generated by Django 5.0 on 2024-01-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_hub",
         "0002_employee_position_"
         "alter_candidate_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
