# Generated by Django 5.0 on 2024-01-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_hub", "0003_salary_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ABD", "Abroad"),
                    ("KYIV", "Kyiv"),
                    ("KHARKIV", "Kharkiv"),
                    ("LVIV", "Lviv"),
                ],
                default="ABD",
                max_length=255,
                null=True,
            ),
        ),
    ]
