# Generated by Django 5.0 on 2024-01-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_hub",
         "0007_remove_comment_candidate_remove_comment_employee_and_more"
         ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salary",
            name="salary_range_end",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="salary_range_start",
        ),
        migrations.AddField(
            model_name="salary",
            name="salary_range",
            field=models.CharField(
                choices=[
                    ("UNDER 500", "Under 500"),
                    ("500 – 1000", "500 – 1000"),
                    ("1000 – 2000", "1000 – 2000"),
                    ("2000 – 3500", "2000 – 3500"),
                    ("3500 – 5000", "3500 – 5000"),
                    ("ABOVE 5000", "Above 5000"),
                ],
                default="Under 500",
                max_length=20,
            ),
        ),
    ]
