# Generated by Django 5.0 on 2024-01-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_hub", "0008_remove_salary_salary_range_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rate",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="rate",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="rate",
            name="employer",
        ),
        migrations.AddField(
            model_name="rate",
            name="vacancy",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="job_hub.vacancy",
            ),
        ),
    ]
