# Generated by Django 5.0 on 2024-01-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_hub", "0009_remove_rate_candidate_"
                    "remove_rate_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="website",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="employer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
