# Generated by Django 5.0 on 2024-01-13 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "job_hub",
            "0011_alter_comment_vacancy_"
            "alter_companyprofile_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="company_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="job_hub.companyprofile",
            ),
        ),
    ]
