# Generated by Django 5.0 on 2024-01-13 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_hub", "0012_employee_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="company_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employers",
                to="job_hub.companyprofile",
            ),
        ),
    ]
