# Generated by Django 5.0 on 2024-01-13 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_hub", "0013_employer_company_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employer",
            unique_together={
                (
                    "employer_first_name", "employer_last_name",
                    "email", "company_name"
                )
            },
        ),
        migrations.RemoveField(
            model_name="employer",
            name="company_profile",
        ),
    ]
