# Generated by Django 5.0 on 2024-01-21 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_hub", "0016_alter_vacancy_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
