# Generated by Django 5.0 on 2024-01-23 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_hub", "0017_vacancy_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rate",
            name="company_profile",
        ),
    ]
