# Generated by Django 5.0 on 2024-01-29 21:42

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hub', '0018_remove_rate_company_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='currency',
            field=models.CharField(choices=[
                ('USD', 'US Dollar'),
                ('EUR', 'Euro'),
                ('GBP', 'British Pound')
            ],
                default='USD',
                max_length=3,
                validators=[django.core.validators.RegexValidator(
                    re.compile('^\\d+(?:,\\d+)*\\Z'),
                    code='invalid',
                    message='Enter only digits separated by commas.')
                ]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_range',
            field=models.CharField(choices=[
                ('UNDER 500', 'Under 500'),
                ('500 – 1000', '500 – 1000'),
                ('1000 – 2000', '1000 – 2000'),
                ('2000 – 3500', '2000 – 3500'),
                ('3500 – 5000', '3500 – 5000'),
                ('ABOVE 5000', 'Above 5000')
            ],
                default='Under 500',
                max_length=20,
                validators=[django.core.validators.RegexValidator(
                    re.compile('^\\d+(?:,\\d+)*\\Z'),
                    code='invalid',
                    message='Enter only digits separated by commas.')]),
        ),
    ]
