# Generated by Django 5.0 on 2024-02-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hub', '0019_alter_salary_currency_alter_salary_salary_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='currency',
            field=models.CharField(choices=[
                ('USD', 'US Dollar'),
                ('EUR', 'Euro'),
                ('GBP', 'British Pound')
            ],
                default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_range',
            field=models.CharField(choices=[
                ('UNDER 500', 'Under 500'),
                ('500 – 1000', '500 – 1000'),
                ('1000 – 2000', '1000 – 2000'),
                ('2000 – 3500', '2000 – 3500'),
                ('3500 – 5000', '3500 – 5000'),
                ('ABOVE 5000', 'Above 5000')
            ],
                default='Under 500', max_length=20),
        ),
    ]
