# Generated by Django 5.0 on 2024-02-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hub', '0020_alter_salary_currency_alter_salary_salary_range'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyprofile',
            unique_together={('company_name', 'website')},
        ),
    ]
