# Generated by Django 5.0 on 2024-02-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hub', '0021_alter_location_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(blank=True, choices=[
                ('ABD', 'Abroad'),
                ('ALL REGIONS', 'All regions'),
                ('CHERKASY', 'Cherkasy'),
                ('CHERNIGIV', 'Chernigiv'),
                ('CHERNIVTSY', 'Chernivtsy'),
                ('CRIMEA', 'Crimea'),
                ('DNIPRO', 'Dnipro'),
                ('DONETSK', 'Donetsk'),
                ('IVANO-FRANKIVSK', 'Ivano-Frankivsk'),
                ('KHARKIV', 'Kharkiv'),
                ('KHERSON', 'Kherson'),
                ('KHMELNITSKY', 'Khmelnitsky'),
                ('KYIV', 'Kyiv'),
                ('KROPYVNYTSKYI', 'Kropyvnytskyi'),
                ('LUGANSK', 'Lugansk'),
                ('LVIV', 'Lviv'),
                ('MYKOLAIV', 'Mykolaiv'),
                ('ODESA', 'Odesa'),
                ('POLTAVA', 'Poltava'),
                ('RIVNE', 'Rivne'),
                ('SUMY', 'Sumy'),
                ('TERNOPIL', 'Ternopil'),
                ('UZHHOROD', 'Uzhhorod'),
                ('VINNITSIA', 'Vinnitsia'),
                ('LUTSK', 'Lutsk'),
                ('ZAPOROZHIA', 'Zaporozhia'),
                ('ZHITOMYR', 'Zhitomyr')
            ],
                                   default='ALL REGIONS',
                                   max_length=255,
                                   null=True
                                   ),
        ),
    ]
