# Generated by Django 5.0 on 2024-02-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hub', '0022_alter_location_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='locations',
            field=models.ManyToManyField(
                related_name='company_profiles',
                to='job_hub.location'
            ),
        ),
    ]
