# Generated by Django 5.0 on 2024-02-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hub', '0023_remove_companyprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_name',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='employees',
                to='job_hub.companyprofile'
            ),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='employers',
                to='job_hub.companyprofile'
            ),
        ),
    ]
