# Generated by Django 5.0 on 2024-02-10 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hub',
         '0024_alter_employee_company_name_alter_employee_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='candidate_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='candidate_last_name',
            new_name='last_name',
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='companyprofile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[
                ('IT', 'Information Technology'),
                ('Healthcare', 'Healthcare'),
                ('Finance', 'Finance'),
                ('Education', 'Education'),
                ('Marketing', 'Marketing'),
                ('Engineering', 'Engineering'),
                ('Sales', 'Sales'),
                ('Customer Service', 'Customer Service'),
                ('Retail', 'Retail'),
                ('Human Resources', 'Human Resources')
            ],
                max_length=50,
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vacancy',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='job_hub.vacancy'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ABD', 'Abroad'),
                    ('ALL REGIONS', 'All regions'),
                    ('CHERKASY', 'Cherkasy'),
                    ('CHERNIGIV', 'Chernigiv'),
                    ('CHERNIVTSY', 'Chernivtsy'),
                    ('CRIMEA', 'Crimea'),
                    ('DNIPRO', 'Dnipro'),
                    ('DONETSK', 'Donetsk'),
                    ('IVANO-FRANKIVSK', 'Ivano-Frankivsk'),
                    ('KHARKIV', 'Kharkiv'),
                    ('KHERSON', 'Kherson'),
                    ('KHMELNITSKY', 'Khmelnitsky'),
                    ('KYIV', 'Kyiv'),
                    ('KROPYVNYTSKYI', 'Kropyvnytskyi'),
                    ('LUGANSK', 'Lugansk'),
                    ('LVIV', 'Lviv'),
                    ('MYKOLAIV', 'Mykolaiv'),
                    ('ODESA', 'Odesa'),
                    ('POLTAVA', 'Poltava'),
                    ('RIVNE', 'Rivne'),
                    ('SUMY', 'Sumy'),
                    ('TERNOPIL', 'Ternopil'),
                    ('UZHHOROD', 'Uzhhorod'),
                    ('VINNITSIA', 'Vinnitsia'),
                    ('LUTSK', 'Lutsk'),
                    ('ZAPOROZHIA', 'Zaporozhia'),
                    ('ZHITOMYR', 'Zhitomyr')
                ],
                default='ALL REGIONS',
                max_length=255,
                null=True,
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='rate',
            name='vacancy',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rate',
                to='job_hub.vacancy'
            ),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('salary_range', 'currency')},
        ),
    ]
