# Generated by Django 5.0 on 2024-02-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'job_hub',
            '0025_rename_candidate_first_name_candidate_first_name_and_more'
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='employer_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='employer_last_name',
            new_name='last_name',
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'last_name', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='employer',
            unique_together={(
                'first_name',
                'last_name',
                'email',
                'company_name'
            )},
        ),
    ]
