name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USE_SQLITE: True
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Display Environment Variables
        run: |
          echo "DB_NAME=${{ env.DB_NAME }}"
          echo "DB_USER=${{ env.DB_USER }}"
          echo "DB_PASSWORD=${{ env.DB_PASSWORD }}"
          echo "DB_HOST=${{ env.DB_HOST }}"
          echo "DB_PORT=${{ env.DB_PORT }}"
      - name: Test with Django test
        run: |
          python manage.py test
      - name: Check migrations
        run: |
          python manage.py makemigrations --check --dry-run
      - name: Code coverage
        run: |
          coverage run --source='.' manage.py test
          coverage report --fail-under=80